### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by jcubic** [c9fe/sirdb#13]
Hi,

I've notice that you don't have a logo, I'm not professional graphic designer but maybe you will like it.

![sir-logo](https://user-images.githubusercontent.com/280241/98855116-c9ba8480-245b-11eb-9bb6-dc012b78f601.png)

For Readme is better to add SVG file (but you can't add png file using upload) you can find it at this link https://jcubic.pl/sir-logo.svg I can also privide smaller size, 

**License**:  If you want to use its license is [Creative Commons Attribution Share-Alike](https://creativecommons.org/licenses/by-sa/3.0/) all you have to do to make it working is to add Attribution my name Jakub T. Jankiewicz with a link to my website https://jcubic.pl.

**Comment by c9fe** [comment]
That's awesome! Thank you. I really appreciate that. Let me consider it more.

**Comment by c9fe** [comment]
I've added it temporarily to get a feel for it and try it on. I might take it down, or might leave it up. Just trying it out. Thank you so much for this! Would it be possible to discuss some changes? If so please mail me cris@dosycorp.com

**Comment by c9fe** [comment]
And I'll just copy your message below to save the license notice:

From https://github.com/jcubic:

----------

Hi,

I've notice that you don't have a logo, I'm not professional graphic designer but maybe you will like it.

![sir-logo](https://user-images.githubusercontent.com/280241/98855116-c9ba8480-245b-11eb-9bb6-dc012b78f601.png)

For Readme is better to add SVG file (but you can't add png file using upload) you can find it at this link https://jcubic.pl/sir-logo.svg I can also privide smaller size, 


**License**:  If you want to use its license is [Creative Commons Attribution Share-Alike](https://creativecommons.org/licenses/by-sa/3.0/) all you have to do to make it working is to add Attribution my name Jakub T. Jankiewicz with a link to my website https://jcubic.pl.
